name: simple-actions-workflow

on:
  push:
    branches:
     main
  pull_request:
    branches: 
     main

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - name: run a oneline script
    - run: echo hello, world!
